---
- name: firewalld rules for ssh
  hosts: all
  tasks:
    - name: install firewalld
      package:
        name: firewalld
        state: latest
    - name: start firewalld service
      service:
        name: firewalld
        enabled: true
        state: started
  
    - name: Allow SSH from specific IP (100.101.47.35)
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="100.101.47.35" port protocol="tcp" port="22" accept'
      notify: reload firewalld

    #- name: Remove default SSH service rule (if it exists)
     # ansible.builtin.command:
     #   cmd: firewall-cmd --permanent --remove-service=ssh
     # ignore_errors: yes  # Ignoring in case SSH service rule doesn't exist
     # notify: reload firewalld

    - name: Block all other SSH traffic on port 22
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --add-rich-rule='rule family="ipv4" port protocol="tcp" port="22" drop'
      notify: reload firewalld

  handlers:
    - name: reload firewalld
      ansible.builtin.command: firewall-cmd --reload
