---
- name: Iptables
  hosts: all
  become: yes
  tasks:
    - name: install iptables;
      package:
        name: iptables-services
        state: latest
    - name: start service iptables
      service: 
        name: iptables
        enabled: true
        state: started

    #- name: Set iptable rule for allowing ssh to port 22 from source x
     # iptables:
      #  chain: INPUT
       # protocol: tcp
        #destination_port: 22
        #state: present
        #source: 100.101.47.100
        #jump: ACCEPT
        #comment: Accept SSH connections from AAP server
    - name: deny all other connections 
      iptables:
        chain: INPUT
        source: "!100.101.47.100"
        protocol: tcp
        destination_port: 22
        jump: DROP
        state: present
        comment: Deny all other SSH connections from other sources except desired source
    #- name: Save current state of the firewall in system file
      #community.general.iptables_state:
       # state: saved
      #  path: /etc/sysconfig/iptables  
    - name: save rule
      shell: sudo iptables-save > /etc/sysconfig/iptables
      notify: restart iptables
  
  handlers:
    - name: restart iptables
      service:
        name: iptables
        state: restarted