---
- name: Iptables
  hosts: all
  tasks:
    - name: install iptables;
      package:
        name: iptables-services
        state: latest
    - name: start service iptables
      service: 
        name: iptables
        enabled: true
        state: started

    - name: Set iptable rule for allowing ssh to port 22 from source x
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        state: present
        source: 100.101.47.100
        jump: ACCEPT
        comment: Accept SSH connections from AAP server
    - name: deny all other connections 
      iptables:
        state: present
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: Deny all other SSH connections from other sources
    - name: save rule
      command:
        cmd: sudo iptables-save
      notify: restart iptables
  handlers: 
    - name: restart iptables
      service:
        name: iptables
        state: restarted
